### ISSUE TITLE
saving profile while using theme-my-login plugin loads wp-email form

### ISSUE THREAD

**Issue by chuckreynolds** [lesterchan/wp-email#7]
just wondering if you may be able to shed some light on this issue even though it's... probably not your plugin's fault... but since you know the inner workings better.. you may know or could point me in the right direction.
Inherited a site with your wp-email plugin and it uses the "Theme My Login" plugin as well.
That uses a shortcode, which is in a page with slug /profile/ on this site, that shows the profile form fields for users to update their name and social stuff etc.  On saving that form it redirects to itself but loads your plugin's email to a friend form (the email-popup.php) form into that profile page and doesn't save the profile info.
I deactivate the wp-email plugin and try the form and it works this time updating the url bar with ".com/profile/?updated=true". 

Again just hoping you may have a thought on why and a quicker route to solution than me trying to reverse engineer both plugins and what the last dev did. Thanks man - appreciate your time.

I left a support ticket on that plugin too but he doesn't seem very responsive.
https://wordpress.org/support/topic/issue-saving-profile-while-using-wp-email-plugin

cheers

**Comment by lesterchan** [comment]
That is wierd, it will only load the form when query_vars email or email_popup is set https://github.com/lesterchan/wp-email/blob/master/wp-email.php#L729

You might want to do a dump to see if Theme My Login modifies anything to the query_var

**Comment by andrewryno** [comment]
Ok the problem is it's actually adding the `email_form` filter to `the_content` when it shouldn't be. I'm guessing there's some non-reliant logic in `email_addfilters`. I'm trying to figure out why it's doing what it's doing and how to fix it.

Steps to reproduce:
1. Install Theme My Login and WP Email
2. Go to /profile/ page and hit save
3. Get response from /profile/ that shows the "share" page for the profile page (so title is "E-Mail 'Your Profile' To A Friend" and it shows the form) instead of processing the request and updating the profile

**Comment by andrewryno** [comment]
Actually.. this might be just a straightforward conflict. It looks like when Theme My Login redirects back to /profile/ it populates the `email` query var with the user email. If that's the case, WP Email is acting as it should.

The problem? I have *zero* idea where that query variable is added. No idea.

**Comment by andrewryno** [comment]
Fixed. Strange problem. Basically, WP-Email sets `email` to a public query var. This results in WordPress transforming the `$_POST['email']` key/value from the form into `$wp_query->query_vars['email']`. However, WP-Email sets `email=1` in the `email_link` function but only checks if `email` is present, not the value.

My hook-fix is thus:

```
add_filter( 'request', 'theme_request' );
function theme_request( $query_vars ) {
    if (isset($query_vars['email'])) {
        $current_user = wp_get_current_user();
        if ($query_vars['email'] === $current_user->user_email) {
            add_filter( 'wp_email_template_redirect', '__return_false' );
        }
    }

    return $query_vars;
}
```

This can be fixed directly in WP-Email two ways:
1. Fix the check for the `email` key to also check for a value of `1` (string or int).
2. Change the trigger key from `email` to something more plugin-specific (LOTS of people I'm sure use the name `email` in a form).

**Comment by chuckreynolds** [comment]
:+1: niiice.

**Comment by lesterchan** [comment]
@andrewryno 

I can't do both because
1. If I changed email to a value of 1, all the URLs will look like (note the one at the back)
```http://localhost:8080/2014/10/17/sadsadas/email/1/```
2. I can't change the email to wp_email or something because the URL will look like ```http://localhost:8080/2014/10/17/sadsadas/wp_email/```
