### ISSUE TITLE
Don't use TEMPLATEPATH in email-standalone.php

### ISSUE THREAD

**Issue by ocean90** [lesterchan/wp-email#8]
`TEMPLATEPATH` points to the parent theme if you're using a child theme. To get the path to the current child theme you can use `STYLESHEETPATH`. (Or better `get_template_directory()` and `get_stylesheet_directory()`.)

I think the template loading should look like this:
```php
if ( $template = locate_template( 'email.php' ) ) {
	include $template;
} elseif ( $template = get_page_template() ) {
	include $template;
} elseif ( $template = get_single_template() ) {
	include $template;
} elseif ( $template = get_index_template() ) {
	include $template;
}
```

This will first check for the file in the child theme and then in the parent theme.

Related: The standalone view should also disable comments: `add_filter('comments_open', '__return_false');`.

Thoughts?

**Comment by lesterchan** [comment]
Thank you @ocean90! I fixed it https://github.com/lesterchan/wp-email/commit/910d15cce01a4ae10d52df1a1489e64930043676 =)
